use crane_highschool;
create table students(student_id int auto_increment primary key,student_aphabetic_order varchar(10),
student_name varchar(80), student_age int, gender varchar(20), nationality varchar(30), 
religion varchar(30), student_order varchar(20), student_class varchar(20));
-- drop table students;
-- show columns from students;
insert into students(student_aphabetic_order,student_name,student_age,gender,
nationality,religion,student_order,student_class)
values
('009', 'ABURA FIONA GIFTY', 14, 'female','ugandan', null, 'day', 'S1'),
('010', 'AKITENG JOAN', 14, 'female', 'ugandan', null, 'day', 'S1'),
('011', 'AMPIYRE JOHN PROSPER',  14, 'female', 'ugandan', null, 'day', 'S1'),
('012', 'ASIIMWE ANNET',  14, 'female', 'ugandan', null, 'day', 'S1'),
('013', 'BAKAKI ABASI',  14, 'male', 'ugandan', null, 'day', 'S1'),
('014', 'IMEDE VIVIAN', 14, 'female', 'ugandan', null, 'day', 'S1'),
('015', 'KASKYA SAUYA', 14 ,'female' ,'ugandan', null ,'day', 'S1'),
('016', 'KOMUGISHA JANET', 14 ,'female', 'ugandan', null ,'day' ,'S1'),
('017','MUTAGA JAMES MULONI', 14,'male', 'ugandan', null ,'day' ,'S1'),
('018','MUWENDO LOUISA', 14, 'male', 'ugandan', null, 'day', 'S1'),
('019', 'NAKALEMBE HANIFAH', 14 ,'female', 'ugandan', null, 'day', 'S1'),
('020','NAKIGANDA DEBORAH MUKISA', 14, 'female', 'ugandan', null, 'day', 'S1'),
('021', 'NAKISEKA PHIONA GIFT', 14, 'female', 'ugandan', null, 'day', 'S1'),
('022', 'NALUKIZA LILLIAN', 14, 'female', 'ugandan', null, 'day', 'S1'),
('023', 'NALUMU RACHEAL ANN', 14 ,'female', 'ugandan', null, 'day', 'S1'),
('024', 'NAMWASE RAHMAT', 14, 'female', 'ugandan', null, 'day', 'S1'),
('025', 'NAYEBALE FAITH', 14 ,'female', 'ugandan', null, 'day', 'S1'),
('026', 'NKONGE ANTHONY' ,14, 'male', 'ugandan', null, 'day', 'S1'),
('027', 'NTEGE ERIA', 14, 'male', 'ugandan', null, 'day', 'S1'),
('028','RIAK GATLUAK JAL', 14, 'male', 'ugandan', null, 'day', 'S1'),
('029','SEMPIIRA GODFREY', 14, 'male', 'ugandan', null, 'day', 'S1'),
('030', 'SSERUWO EDDRINE' ,14, 'male', 'ugandan', null, 'day', 'S1'),
('009', 'ATIM GLORIA', 15, 'female', 'ugandan', null, 'day', 'S2'),
('010', 'BBOOSA RICHARD', 15, 'male', 'ugandan', null, 'day', 'S2'),
('011', 'KAMUSIME JORDAN', 15, 'male', 'ugandan', null, 'day', 'S2'),
('012', 'MUHANGUZI ANTHLEM', 15, 'male', 'ugandan', null, 'day', 'S2'),
('013', 'MULUNGI NICHOLAS', 15, 'male', 'ugandan', null, 'day', 'S2'),
('014', 'NANOZI CATHERINE', 15, 'female', 'ugandan', null, 'day', 'S2'),
('017', 'AHIMBISIBWE NICHOLAS MOTINA', 16, 'male', 'ugandan', null, 'day', 'S3'),
('018', 'MUANGUZI ZION',  16, 'male', 'ugandan', null, 'day', 'S3'),
('019', 'NAMUGANZI ANISHA', 16, 'female','ugandan', null,'day', 'S3'),
('020', 'NASANDE BETTY',16, 'female', 'ugandan', null,'day','S3'),
('021', 'NYENGER MARY', 16, 'female', 'ugandan', null,'day', 'S3'),
('022', 'TRUYAMUREBA GRAHAM', 16 ,'male','ugandan', null,'day', 'S3'),
('023', 'WAMALA JOHNATHAN',16, 'male','ugandan', null, 'day','S3'),
('001', 'AHUMUZA BRIAN',18, 'male', 'ugandan', null,'day','S4'),
('002', 'EYOTARU SUZAN',18, 'female', 'ugandan', null, 'day','S4'),
('003', 'MUTEBI MARTIN',18, 'male','ugandan', null,'day', 'S4'),
('004', 'ODONGO AMBROSE', 18, 'male','ugandan', null,'day','S4'),
('005', 'OKELLO BAZIL',18, 'male','ugandan', null,'day','S4');
select * from students;